### ISSUE TITLE
CSS compilation error

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/textlab#168]
When attempting to log in to app.textlab.org, the following error is produced. A refresh seems to clear it up.

![screen shot 2017-09-21 at 10 34 51 am](https://user-images.githubusercontent.com/18423533/30701553-8b17b08a-9eb8-11e7-9ffe-42f1fa998f27.png)

**Comment by NickLaiacona** [comment]
I think this is likely do to an interaction between the JVM, JRuby, Rails, and the Heroku server environment.

**Comment by tezcatlipoca** [comment]
@NickLaiacona I'm still working on this, but I haven't been able to generate the error.

It does seem related to the asset pipeline because of the "error compiling CSS",  this is odd because this runs cleanly (except for the warnings):
**heroku run rake assets:precompile --trace**


Question: can we try precompiling the assets instead of generating them at runtime? (IE any reason we need them to dynamically compile?)

Related: Any other info on how to generate this error? Is it only on login? Have you seen it on dev or local or only on production?

**Comment by NickLaiacona** [comment]
It should be only compiling them once, since the RAILS_ENV variable is set
to "production". Maybe try pushing a trivial change to staging, see if that
can provoke it into this state? If so.. perhaps we just run *heroku run
rake assets:precompile *immediately after pushing the new code as part of
our deployment procedure.

**Comment by tezcatlipoca** [comment]
I don't see the error if I run it local or production, even if I run a 'clean' first... 

but in any case (I think) that's what I"m suggesting, we run precompile manually instead of making the assets generate dynamically. We only need to do this if we change the CSS - we check the /public/assets folder into the repo and heroku shouldn't try and build them again. Still doesn't pinpoint what's wrong but it's a workaround to spending more time hunting down the error.

**Comment by tezcatlipoca** [comment]
Can reproduce by: pushing to PR instance, restarting the instance. 

Things that don't seem to work: Precompiling the assets (grrr)

Suspicion: there's a sass version issue. there are various attempts at things in the "as-sidebar" branch
